# Generated by Django 3.1.1 on 2020-10-30 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('abreviatura', models.CharField(max_length=5)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(verbose_name='Date creatio')),
                ('fecha_modificacion', models.DateTimeField(verbose_name='Date update')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('abreviatura', models.CharField(max_length=5)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(verbose_name='Date creatio')),
                ('fecha_modificacion', models.DateTimeField(verbose_name='Date update')),
                ('id_pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afiliados.paises')),
            ],
        ),
        migrations.CreateModel(
            name='Afiliados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('numero_movil', models.BigIntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=70)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(verbose_name='Date creatio')),
                ('fecha_modificacion', models.DateTimeField(verbose_name='Date update')),
                ('id_ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afiliados.ciudades')),
            ],
        ),
    ]
